name: number_trivia
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  data_connection_checker_tv: ^0.3.5-nullsafety
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  http: ^0.13.5
  shared_preferences: ^2.0.15

dev_dependencies:
  freezed: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mockito: ^5.3.2

flutter:
  uses-material-design: true
